AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation stack to provision AWS Glue resources (DB, Job, Crawlers)

Resources:

  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: glue-service-role-niv
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess
        - arn:aws:iam::aws:policy/AmazonAthenaFullAccess

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: vi_data_db

  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: process-data-job-niv
      Role: !GetAtt GlueServiceRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: "s3://data-engineer-assignment-niv/scripts/stock_etl_pipeline.py"
        PythonVersion: 3
      GlueVersion: "4.0"
      DefaultArguments:
        "--TempDir": "s3://data-engineer-assignment-niv/temp/"
        "--output_path": "s3://data-engineer-assignment-niv/processedData/"
        "--enable-metrics": "true"
      MaxRetries: 0
      Timeout: 10
      NumberOfWorkers: 2
      WorkerType: G.1X

  GlueCrawlerAvgDailyStock:
    Type: AWS::Glue::Crawler
    Properties:
      Name: output-crawler-AvgDailyStock
      Role: !GetAtt GlueServiceRole.Arn
      DatabaseName: !Ref GlueDatabase
      Targets:
        S3Targets:
          - Path: "s3://data-engineer-assignment-niv/processedData/AvgDailyStock/"
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DEPRECATE_IN_DATABASE
      Schedule:
        ScheduleExpression: "cron(10,22 0 * * ? *)"  # twice a day

  GlueCrawlerHighestWorth:
    Type: AWS::Glue::Crawler
    Properties:
      Name: output-crawler-HighestWorth
      Role: !GetAtt GlueServiceRole.Arn
      DatabaseName: !Ref GlueDatabase
      Targets:
        S3Targets:
          - Path: "s3://data-engineer-assignment-niv/processedData/HighestWorth/"
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DEPRECATE_IN_DATABASE
      Schedule:
        ScheduleExpression: "cron(10,22 0 * * ? *)"  # twice a day

  GlueCrawlerStockStd:
    Type: AWS::Glue::Crawler
    Properties:
      Name: output-crawler-StockStd
      Role: !GetAtt GlueServiceRole.Arn
      DatabaseName: !Ref GlueDatabase
      Targets:
        S3Targets:
          - Path: "s3://data-engineer-assignment-niv/processedData/StockStd/"
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DEPRECATE_IN_DATABASE
      Schedule:
        ScheduleExpression: "cron(10,22 0 * * ? *)"  # twice a day

  GlueCrawlerTopThree:
    Type: AWS::Glue::Crawler
    Properties:
      Name: output-crawler-TopThree
      Role: !GetAtt GlueServiceRole.Arn
      DatabaseName: !Ref GlueDatabase
      Targets:
        S3Targets:
          - Path: "s3://data-engineer-assignment-niv/processedData/TopThree/"
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DEPRECATE_IN_DATABASE
      Schedule:
        ScheduleExpression: "cron(10,22 0 * * ? *)"  # twice a day
